# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReduxFirstTestProj' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReSwift'
  
  target 'ReduxFirstTestProjTests' do
      inherit! :search_paths
      pod 'ReSwift'
  end

  # Pods for StudyDriveTestProject

end
